Lesson3
ilya-frolov/freeit pull request #3
Opened 2022-06-27 16:33 UTC by ilya-frolov

Hi everybody. It would be nice if you find free time for verification and evaluation my HomeWorks.

This branch consists of the next tasks:
1. Print how much various time types values in 4500 seconds.
2. Make a mirrored number. I provided two different solution types.
3. Greet a person according to a gender and  an age.
4. Provide five ways for String variable creation.

Sincerely yours

2022-06-30 10:21 UTC, RomanKashenok requested changes

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_FiveWaysString.java
> +        System.out.println(letter1 + "" + letter2 + " " + letter3 + "" + letter4 + "" + letter5 + " "
столько мучался, а строку в итоге так и не составил. получил кучу ненужных чаров и все

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_FiveWaysString.java
> +        System.out.println("\nMethod 5_2:");
аналогично

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_FiveWaysString.java
> +    }
из всех 80ти строк кода реально только 2 способа создать строку. Остальное - протезирование зуба через прямую кишку

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_GreetingGenderAge.java
> +        System.out.println("\nThe program is completed successfully.");
сильно перегружено выводами и кучей ненужной логики

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +        int n4 = n - n1 * 1000 - n2 * 100 - n3 * 10;// the fourth digit of the given number
переиспользуй свои вычисления ((n - n1 * 1000) например)

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +        System.out.println(n4 + "" + n3 + "" + n2 + "" + n1);// the mirrored number
ну и в итоге ты просто вывел цифры, не составляя число

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +         */
давай сюда сбрасывать только то, что нужно. Оч много времени занимает отделение нужного от ненужного

2022-06-30 10:21 UTC, RomanKashenok commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_TimeTask.java
> +        System.out.println("\nThe program is completed successfully!");
зис ис прям гуд ))
ток комментарии на элементарные, понятные из кода строки писать не стоит - засоряет общую картину

2022-07-01 14:55 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_TimeTask.java
> +        System.out.println("\nThe program is completed successfully!");
Оки

2022-07-01 15:05 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +         */
Лан

2022-07-01 15:12 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +        int n4 = n - n1 * 1000 - n2 * 100 - n3 * 10;// the fourth digit of the given number
Сделал.

2022-07-01 15:12 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_MirrorNumber.java
> +        System.out.println(n4 + "" + n3 + "" + n2 + "" + n1);// the mirrored number
Исправил.

2022-07-01 15:45 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_FiveWaysString.java
> +    }
Мне кажется, я тебя понял. Переслушал твое занятие, переделал код.

2022-07-01 15:47 UTC, ilya-frolov commented on HomeWorkTask3/src/com/ilyafrolov/lesson3/HomeWorkTask3_GreetingGenderAge.java
> +        System.out.println("\nThe program is completed successfully.");
Вот тут, честно, нужно пояснение, что именно не нужно? Возможно часть, где я при выводе листа имен точку в конце ставлю с помощью алгоритма?

2022-07-07 11:26 UTC, RomanKashenok approved these changes

2022-08-11 15:37 UTC, merged