Lesson 4
ilya-frolov/freeit pull request #4
Opened 2022-06-28 14:12 UTC by ilya-frolov

Hi everybody. I would appreciate your verification and assessment of my HomeWorks.

This branch consists of the next tasks:

1. Verify if a round cover is enough large for covering a rectangular hole fully.
2. Based on the task from PDF tutorial make a program for factorial calculation.
3. Calculate a factorial of a number in the bounds between 10 and 15 without using recursion. 
4. Verify if the given number is simple.
5. Make program for printing a month and the corresponding season.
6. Verify if a number is three-digit one, if it's last digit is 7, if the number is even.
7. Print the number of rubles and the word "rubley" in the correct padej.
8. Find the  sum of n first integers, divided by three.

Sincerely yours

2022-06-30 10:32 UTC, RomanKashenok requested changes

2022-06-30 10:32 UTC, RomanKashenok commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_ObtainNumbersCharacteristics.java
> +            }
или 7 == n % 10

2022-06-30 10:32 UTC, RomanKashenok commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_SumNumbersDividedThree.java
> +        int j = i;
в задании написано "первых", т.е. 3 6 9 12 15 18 ... зачем стартовать непонятно откуда?

2022-06-30 11:17 UTC, ilya-frolov commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_SumNumbersDividedThree.java
> +        int j = i;
В задании не указано, "первых" начиная с нуля или начиная с 1000, поэтому я сделал версию, когда не важно откуда начинается отсчет.

2022-06-30 13:42 UTC, mrchernova reviewed
Correct mistake in IfNumberSimple task, please

2022-06-30 13:42 UTC, mrchernova commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_IfNumberSimple.java
> +        if (num != 2 && num !=3 && num % 2 == 0 || num % 3 == 0 || num % 5 == 0 || num % 7 == 0 || num % 11 == 0 || num % 13 == 0){
Не, не работает. 
Например, 15 - простое число

2022-06-30 19:52 UTC, ilya-frolov commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_PadejRubles.java
> +            }
Исправил

2022-06-30 19:57 UTC, RomanKashenok commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_ObtainNumbersCharacteristics.java
> +            }
а мой вариант и не ограничивается трехзначными числами )

2022-06-30 20:01 UTC, RomanKashenok requested changes

2022-06-30 20:01 UTC, ilya-frolov commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_SumNumbersDividedThree.java
> +            if (j % 3 == 0) {
Точно, супер, исправил.

2022-06-30 20:02 UTC, ilya-frolov commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_PadejRubles.java
> +            }
Да, думал думал, ниче лучше пока не придумал)

2022-06-30 20:03 UTC, RomanKashenok approved these changes

2022-07-01 06:59 UTC, mrchernova commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_IfNumberSimple.java
> +        if (num != 2 && num !=3 && num % 2 == 0 || num % 3 == 0 || num % 5 == 0 || num % 7 == 0 || num % 11 == 0 || num % 13 == 0){
Точно, что-то я тупанула  вчера

2022-07-01 07:00 UTC, mrchernova approved these changes

2022-07-01 14:53 UTC, ilya-frolov commented on HomeWorkTask4/src/com/ilyafrolov/lesson4/HomeWorkTask4_IfNumberSimple.java
> +        int[] numArray = new int[num + 1];
Убрал)

2022-08-11 15:37 UTC, merged